before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/poslog
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
brews:
  - tap:
      owner: winebarrel
      name: homebrew-poslog
    homepage: https://github.com/winebarrel/poslog
    description: Parser to extract SQL from postgresql.log
    license: MIT
    install: |
      bin.install 'poslog'
